apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gitops-app.fullname" . }}-db-secret

  labels:
    {{- include "gitops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend

type: Opaque

stringData:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}